### ISSUE TITLE
non funziona

### ISSUE THREAD

**Issue by vivi202** [neothematrix/bigtower-cp-provider#2]
mi da questo errore nei log 
07-10 21:01:44 ERROR [o.core.downloaders.deluge] Failed to add torrent file Men In Black II 2002 ITA AC3 DTS ENG BluRay 1080p x264 BTR.cp(tt0120912).torrent: not a valid bencoded string Traceback (most recent call last):
  File "/var/www/CouchPotatoServer/couchpotato/core/downloaders/deluge.py", line 258, in add_torrent_file
    torrent_id = self._check_torrent(False, torrent)
  File "/var/www/CouchPotatoServer/couchpotato/core/downloaders/deluge.py", line 322, in _check_torrent
    info = bdecode(torrent)["info"]
  File "/var/www/CouchPotatoServer/libs/bencode/__init__.py", line 68, in bdecode
    raise BTFailure("not a valid bencoded string")
BTFailure: not a valid bencoded string

**Comment by neothematrix** [comment]
ciao, se lo scarichi a mano quel torrent direttamente dal sito riesci a prenderlo senza problemi?

**Comment by vivi202** [comment]
no, ho capito grazie lo stesso scusa per il disturbo.
